In [ ]:
# import library
import pandas as pd

In [ ]:
# import data
salary = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Salary%20Data.csv')

In [ ]:
salary.head()

   Experience Years  Salary
0               1.1   39343
1               1.2   42774
2               1.3   46205
3               1.5   37731
4               2.0   43525

In [ ]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Experience Years  40 non-null     float64
 1   Salary            40 non-null     int64
dtypes: float64(1), int64(1)
memory usage: 768.0 bytes

In [ ]:
salary.describe()

       Experience Years         Salary
count         40.000000      40.000000
mean           5.152500   74743.625000
std            2.663715   25947.122885
min            1.100000   37731.000000
25%            3.200000   56878.250000
50%            4.600000   64472.500000
75%            6.875000   95023.250000
max           10.500000  122391.000000

In [ ]:
salary.columns

Index(['Experience Years', 'Salary'], dtype='object')

In [ ]:
salary.shape

(40, 2)

In [ ]:
# Define target (y) and features (x)

In [ ]:
y = salary['Salary' ]
x = salary[['Experience Years']]

In [ ]:
x.shape

(40, 1)

In [ ]:
y.shape

(40,)

In [ ]:
# Train test split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state = 2529)
x_train

    Experience Years
28               6.5
31               7.9
34               8.7
20               4.7
4                2.0
3                1.5
18               4.3
26               6.0
2                1.3
22               5.1
35               9.0
7                2.9
39              10.5
30               7.1
10               3.2
0                1.1
9                3.2
13               3.8
5                2.2
37               9.6
23               5.3
25               5.9
21               4.9
24               5.5
8                3.0
36               9.5
15               4.0
32               8.2

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((30, 1), (10, 1), (30,), (10,))